<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Ramsey\Uuid\Uuid;

class MenuBot extends Model
{
    protected $guarded = [];
    public $incrementing = false;
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::creating(function ($model) {
            if (empty($model->id))
                $model->id = setOrderedUUID($model);
        });
    }
    public function keywords()
    {
        return $this->hasMany(MenuKeyword::class,'menu_id');
    }

    public function parent()
    {
        return $this->belongsTo(MenuBot::class,'parent_id');
    }

    public function childs()
    {
        return $this->hasMany(MenuBot::class,'parent_id');
    }
}
